### PR TITLE
Linter-Setup

### PR DESCRIPTION
**Pull request by esmiz-dream**
### Linter-Setup
In This pull Request I:
. Added home page HTML structure
. Added styling of the home page
. Added test md

### CODE REVIEW

**Review by vickymarz — CHANGES_REQUESTED** [review]
Hi @esmiz-dream, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 

## Required Changes ♻️

- [ ]  I will recommend you always write a well-descriptive pull request title describing the feature or project you are working on. Instead of writing `My First Pull Request` as your pull request title which is not clear, you can write `Hello Microverse` or ` LInter setup` which is more descriptive 😄 .

- [ ]  I will recommend you always write a well-descriptive branch name describing the feature or project you are working on. Instead of writing `add-home-styling` as branch-name, you can write `hello-microverse` or ` linter-setup` which is more descriptive 😄 .

- [ ] I will strongly recommend you customize your readme to contain relevant information about your project. Kindly edit all the sections of your readme and add information relating to your project so that your repo will look more professional. e.g future feature section 👍🏽 

- [ ] I will strongly recommend you always capitalize the first letter of your commit messages which is a standard for writing commit messages 😄 . These will make your repo look professional 👍🏽 

- [ ]  Kindly make sure that the `test.md` file is actually ignored by `git` and is not present in your GitHub repository.
You should first untrack it by `git`, and then add it to the `.gitignore` file 😄

To untrack the file, run git `rm --cached test.md` in your terminal

follow these [lesson](https://github.com/microverseinc/linters-config/tree/master/html-css) step-by-step to setup linters 👍🏽  

- **Please note that you are not required to merge your pull request until it has been approved by a code reviewer and it reflects as approved on your dashboard. Kindly take note of these.**

_Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by esmiz-dream** [comment]
Hallo @vickymarz
thank you for your constructive comments and recommendations.
i get all are valuables.
how I can change the branch name with out losing the pull request I created.
in my previous, pull request and try to change the name of the branch after that I lost the pull request.
thank you

**Comment by vickymarz** [comment]
@esmiz-dream you will loose the pr. You csn add link of the old pr in your new pr

**Comment by esmiz-dream** [comment]
where can i add the previous pr link and did I miss the pr ruls of the microverss

**Pull request closed without merging**
